const foods = [
  {id:'dosa',name:'Masala Dosa',category:'South Indian',price:80,rating:4.8,time:'15 min',desc:'Crispy golden dosa with flavourful potato masala, chutney and sambar.',img:'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=900&q=85',tag:'Most Loved'},
  {id:'pizza',name:'Paneer Pizza',category:'Pizza',price:220,rating:4.7,time:'25 min',desc:'Charred crust topped with paneer, peppers and stretchy cheese.',img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',tag:'Chef\'s Pick'},
  {id:'burger',name:'Chicken Burger',category:'Burgers',price:180,rating:4.6,time:'20 min',desc:'Juicy grilled chicken, crisp lettuce and house sauce in a toasted bun.',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',tag:'Popular'},
  {id:'biryani',name:'Chicken Biryani',category:'Comfort Food',price:250,rating:4.9,time:'30 min',desc:'Fragrant basmati rice layered with spiced chicken and fresh herbs.',img:'https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=900&q=85',tag:'Popular'},
  {id:'noodles',name:'Veg Noodles',category:'Chinese',price:140,rating:4.5,time:'18 min',desc:'Wok-tossed noodles with colourful vegetables and sesame.',img:'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=900&q=85',tag:'15 Min'},
  {id:'pasta',name:'Pasta Alfredo',category:'Italian',price:210,rating:4.7,time:'22 min',desc:'Silky parmesan cream sauce, herbs and perfectly cooked pasta.',img:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',tag:'Chef\'s Pick'},
  {id:'brownie',name:'Chocolate Brownie',category:'Desserts',price:120,rating:4.8,time:'10 min',desc:'Rich fudgy chocolate brownie with a crackly top.',img:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=85',tag:'Sweet'},
  {id:'bowl',name:'Fresh Fruit Bowl',category:'Healthy',price:150,rating:4.6,time:'8 min',desc:'Seasonal fruit, mint and a bright citrus drizzle.',img:'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=85',tag:'Healthy'},
  {id:'idli',name:'Idli Sambar',category:'Breakfast',price:70,rating:4.7,time:'12 min',desc:'Soft steamed idlis with hearty sambar and coconut chutney.',img:'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=85',tag:'Classic'},
  {id:'wrap',name:'Chicken Wrap',category:'Healthy',price:160,rating:4.5,time:'16 min',desc:'Spiced chicken, crunchy salad and yogurt dressing in a warm wrap.',img:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',tag:'Fresh'},
  {id:'rice',name:'Veg Fried Rice',category:'Chinese',price:130,rating:4.4,time:'15 min',desc:'Smoky wok-fried rice with vegetables, garlic and spring onion.',img:'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=85',tag:'15 Min'},
  {id:'smoothie',name:'Mango Smoothie',category:'Beverages',price:110,rating:4.8,time:'7 min',desc:'Alphonso mango blended with yogurt for a sunny, creamy sip.',img:'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=85',tag:'Seasonal'}
];
const recipeCuisines = {dosa:'South Indian',pizza:'Italian',burger:'American',biryani:'Indian',noodles:'Chinese',pasta:'Italian',brownie:'Desserts',bowl:'Healthy',idli:'South Indian',wrap:'Healthy',rice:'Chinese',smoothie:'Healthy'};
const recipes = foods.map((food,i) => ({...food, cuisine: recipeCuisines[food.id],difficulty:i%3===0?'Easy':i%3===1?'Medium':'Easy', prep:i%2?'10 min':'5 min', servings:2, ingredients:['Fresh ingredients','Aromatic spices','Herbs and seasoning','A finishing drizzle']}));

const money = n => `₹${Number(n).toFixed(0)}`;
function cartData(){ return JSON.parse(localStorage.getItem('foodiego-cart') || '[]'); }
function saveCart(cart){ localStorage.setItem('foodiego-cart', JSON.stringify(cart)); updateCartCount(); }
function updateCartCount(){ const count=cartData().reduce((sum,item)=>sum+item.qty,0); document.querySelectorAll('.cart-count').forEach(el=>el.textContent=count); }
function toast(message){ const el=document.getElementById('toast'); if(!el)return; el.querySelector('.toast-body').textContent=message; bootstrap.Toast.getOrCreateInstance(el).show(); }
function addToCart(food, qty=1, custom='Standard'){ const cart=cartData(); const key=`${food.id}-${custom}`; const found=cart.find(item=>item.key===key); if(found) found.qty+=qty; else cart.push({...food,key,custom,qty}); saveCart(cart); toast(`${food.name} added to your cart`); }
function foodCard(food){ return `<div class="col-sm-6 col-lg-4 fade-up"><article class="food-card"><div class="position-relative overflow-hidden"><img src="${food.img}" alt="${food.name}"><span class="badge-soft position-absolute top-0 start-0 m-3">${food.tag}</span></div><div class="card-body"><div class="d-flex justify-content-between gap-2"><h3 class="h5 mb-1">${food.name}</h3><span class="price">${money(food.price)}</span></div><p class="meta mb-2">${food.desc}</p><div class="d-flex justify-content-between align-items-center"><span class="rating">★ ${food.rating} <small class="meta"> · ${food.time}</small></span><button class="btn btn-sm btn-brand add-food" data-id="${food.id}">Add +</button></div><a class="stretched-link" href="food-details.html?id=${food.id}" aria-label="View ${food.name}"></a></div></article></div>`; }
function recipeCard(recipe){ return `<div class="col-sm-6 col-lg-3 fade-up"><article class="recipe-card"><img src="${recipe.img}" alt="${recipe.name}"><div class="card-body"><span class="eyebrow">${recipe.cuisine}</span><h3 class="h5 mt-1">${recipe.name}</h3><p class="meta mb-3">★ ${recipe.rating} · ${recipe.time} · ${recipe.difficulty}</p><a class="btn btn-outline-brand btn-sm" href="recipe-detail.html?id=${recipe.id}">View recipe</a></div></article></div>`; }
function renderFoodList(list, target){ const el=document.querySelector(target); if(el) el.innerHTML=list.length?list.map(foodCard).join(''):`<div class="col-12 text-center py-5"><h3>No matches yet</h3><p class="meta">Try another search or category.</p></div>`; }
function renderRecipeList(list,target){ const el=document.querySelector(target); if(el) el.innerHTML=list.length?list.map(recipeCard).join(''):`<div class="col-12 text-center py-5"><h3>No recipes found</h3></div>`; }
function initHome(){ renderFoodList(foods.slice(0,6),'#popular-foods'); renderRecipeList(recipes.slice(2,6),'#trending-recipes'); }
function initMenu(){ let current=foods; renderFoodList(current,'#food-grid'); const apply=()=>{ const q=(document.querySelector('#food-search').value||'').toLowerCase(); const cat=document.querySelector('.filter-btn.active')?.dataset.cat||'All'; current=foods.filter(f=>(cat==='All'||f.category===cat||cat==='Breakfast'&&f.category==='Breakfast') && `${f.name} ${f.desc}`.toLowerCase().includes(q)); renderFoodList(current,'#food-grid'); }; document.querySelector('#food-search').addEventListener('input',apply); document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');apply();})); }
function initRecipes(){ const apply=()=>{const q=(document.querySelector('#recipe-search').value||'').toLowerCase();const cat=document.querySelector('.filter-btn.active')?.dataset.cat||'All';renderRecipeList(recipes.filter(r=>(cat==='All'||r.cuisine===cat||cat==='Quick Recipes'&&parseInt(r.time)<=15)&&`${r.name} ${r.cuisine}`.toLowerCase().includes(q)),'#recipe-grid');}; apply(); document.querySelector('#recipe-search').addEventListener('input',apply); document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');apply();})); }
function renderDetail(){ const id=new URLSearchParams(location.search).get('id')||'dosa'; const food=foods.find(f=>f.id===id)||foods[0]; document.querySelectorAll('[data-food-name]').forEach(e=>e.textContent=food.name); document.querySelectorAll('[data-food-img]').forEach(e=>{e.src=food.img;e.alt=food.name;}); document.querySelector('[data-food-desc]').textContent=food.desc; document.querySelector('[data-food-price]').textContent=money(food.price); document.querySelector('[data-food-rating]').textContent=`★ ${food.rating}`; document.querySelector('[data-add-detail]').addEventListener('click',()=>addToCart(food)); document.querySelector('[data-customize]').href=`customize.html?id=${food.id}`; }
function initCustomize(){ const food=foods.find(f=>f.id===(new URLSearchParams(location.search).get('id')||'dosa'))||foods[0]; document.querySelector('[data-food-img]').src=food.img; document.querySelector('[data-food-name]').textContent=food.name; document.querySelector('[data-base]').textContent=money(food.price); const update=()=>{let extras=0;document.querySelectorAll('.extra:checked').forEach(x=>extras+=Number(x.dataset.price));const qty=Number(document.querySelector('#quantity').value);document.querySelector('[data-extras]').textContent=money(extras);document.querySelector('[data-qty]').textContent=qty;document.querySelector('[data-total]').textContent=money((food.price+extras)*qty);}; document.querySelectorAll('.extra,.size,.spice').forEach(x=>x.addEventListener('change',update)); document.querySelector('#minus').addEventListener('click',()=>{const input=document.querySelector('#quantity');input.value=Math.max(1,Number(input.value)-1);update();}); document.querySelector('#plus').addEventListener('click',()=>{const input=document.querySelector('#quantity');input.value=Number(input.value)+1;update();}); document.querySelector('#custom-add').addEventListener('click',()=>{const extras=[...document.querySelectorAll('.extra:checked')].map(x=>x.value).join(', ')||'No extras';const size=document.querySelector('.size:checked')?.value||'Regular';const spice=document.querySelector('.spice:checked')?.value||'Mild';addToCart({...food,price:food.price+[...document.querySelectorAll('.extra:checked')].reduce((s,x)=>s+Number(x.dataset.price),0)},Number(document.querySelector('#quantity').value),`${size}, ${spice}${extras==='No extras'?'':', '+extras}`);}); update(); }
function initCart(){ const root=document.querySelector('#cart-items'); const summary=document.querySelector('#cart-summary'); let discount=0; const render=()=>{const cart=cartData(); if(!cart.length){root.innerHTML='<div class="text-center py-5"><div class="display-3">🛒</div><h2>Your cart is waiting</h2><p class="meta">Add something delicious to get started.</p><a class="btn btn-brand" href="menu.html">Browse menu</a></div>';summary.innerHTML='';return;} root.innerHTML=cart.map((item,i)=>`<div class="cart-item d-flex gap-3 align-items-center"><img src="${item.img}" alt="${item.name}"><div class="flex-grow-1"><h3 class="h6 mb-1">${item.name}</h3><p class="meta mb-2">${item.custom}</p><div class="qty-control"><button data-action="dec" data-index="${i}">−</button><span>${item.qty}</span><button data-action="inc" data-index="${i}">+</button></div></div><div class="text-end"><strong>${money(item.price*item.qty)}</strong><button class="btn btn-link text-danger d-block p-0" data-action="remove" data-index="${i}">Remove</button></div></div>`).join(''); const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0), delivery=subtotal?35:0,total=subtotal+delivery-discount;summary.innerHTML=`<h2 class="h4">Order summary</h2><div class="d-flex justify-content-between"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="d-flex justify-content-between"><span>Delivery fee</span><strong>${money(delivery)}</strong></div><div class="d-flex justify-content-between text-success"><span>Discount</span><strong>-${money(discount)}</strong></div><hr><div class="d-flex justify-content-between h5"><span>Total</span><strong>${money(total)}</strong></div><a href="tracking.html" class="btn btn-brand w-100 mt-3">Proceed to Checkout</a>`;}; root.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const cart=cartData(),i=Number(btn.dataset.index);if(btn.dataset.action==='remove')cart.splice(i,1);if(btn.dataset.action==='inc')cart[i].qty++;if(btn.dataset.action==='dec')cart[i].qty=Math.max(1,cart[i].qty-1);saveCart(cart);render();});document.querySelector('#coupon-form')?.addEventListener('submit',e=>{e.preventDefault();if(document.querySelector('#coupon').value.trim().toUpperCase()==='FOOD10'){discount=cartData().reduce((s,x)=>s+x.price*x.qty,0)*.1;document.querySelector('#coupon-message').textContent='FOOD10 applied: 10% off your order.';document.querySelector('#coupon-message').className='text-success small mt-2';render();}else{document.querySelector('#coupon-message').textContent='That coupon is not valid.';document.querySelector('#coupon-message').className='text-danger small mt-2';}});render(); }
function initAuth(){ document.querySelector('form[data-auth]')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget, message=document.querySelector('#form-message');if(!form.checkValidity()){form.classList.add('was-validated');return;}if(form.dataset.auth==='register'&&document.querySelector('#password').value!==document.querySelector('#confirm-password').value){message.textContent='Passwords do not match.';message.className='text-danger small';return;}message.textContent=form.dataset.auth==='login'?'Welcome back to FoodieGo!':'Account created successfully!';message.className='text-success small';}); }
function initTracking(){let status=Number(localStorage.getItem('foodiego-status')||1);const render=()=>{document.querySelectorAll('.step').forEach((step,i)=>{step.classList.toggle('done',i<status);step.classList.toggle('current',i===status);});document.querySelector('#status-label').textContent=['Order confirmed','Food is being prepared','Out for delivery','Delivered'][status];};document.querySelector('#update-status').addEventListener('click',()=>{status=Math.min(3,status+1);localStorage.setItem('foodiego-status',status);render();toast(status===3?'Order delivered!':'Order status updated');});render(); }
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();document.addEventListener('click',e=>{const btn=e.target.closest('.add-food');if(!btn)return;e.preventDefault();e.stopPropagation();addToCart(foods.find(f=>f.id===btn.dataset.id));});const page=document.body.dataset.page;if(page==='home')initHome();if(page==='menu')initMenu();if(page==='recipes')initRecipes();if(page==='detail')renderDetail();if(page==='customize')initCustomize();if(page==='cart')initCart();if(page==='auth')initAuth();if(page==='tracking')initTracking();});
